feat: add multiple datasets (hacker, git, food, finance, company)

diff --git a/.github/workflows/deploy-to-server.yml b/.github/workflows/deploy-to-server.yml
--- a/.github/workflows/deploy-to-server.yml
+++ b/.github/workflows/deploy-to-server.yml
@@ -117,3 +117,22 @@ jobs:
             cat response.json
             exit 1
           fi
+
+  notification:
+    name: Send Notification
+    runs-on: ubuntu-latest
+    needs: execute
+    steps:
+      - name: Notify
+        run: |
+          response=$(curl -s -o response.json -w "%{http_code}" \
+            -X POST "${{ secrets.WEBHOOK }}" \
+            -H "Authorization: Bearer ${{ secrets.WEBHOOK_SECRET }}" \
+            -H "Content-Type: application/json" \
+            -d '{"command": "sendDeploymentNotification", "payload": {"project": "Mockly", "target": "Remote Server", "status":"Success", "version": "${{ env.VERSION }}"}}')
+
+          if [ "$response" -ne 200 ]; then
+            echo "Error during Send Notification. Response code: $response"
+            cat response.json
+            exit 1
+          fi
